import Link from "next/link"

import AuthorityQuote from "@/components/AuthorityQuote"
import ScrollReveal from "@/components/ScrollReveal"

type LaunchPath = {
  href: string
  cta: string
}

const PATHS: LaunchPath[] = [
  {
    href: "/callio",
    cta: "Start with Callio",
  },
  {
    href: "/agents",
    cta: "Explore pre-built agents",
  },
]

export default function LaunchPaths() {
  return (
    <section className="lv-launch" aria-labelledby="launch-paths-title">
      <div className="lv-launch-inner">
        <ScrollReveal>
          <div className="lv-launch-intro">
            <div>
              <div className="lv-philosophy-eyebrow">
                <span className="lv-eyebrow-dot" aria-hidden="true" />
                <span>Two ways to launch</span>
              </div>
            </div>
          </div>
        </ScrollReveal>

        {/* The section's statement is the regulator's, not ours: rendered
            statically (outside ScrollReveal) so it is visible without JS. */}
        <h2 id="launch-paths-title" className="lv-authq-sr">Two ways to launch</h2>
        <AuthorityQuote
          embedded
          align="center"
          variant="olive"
          className="lv-launch-quote"
          quote="Firms are responsible for their communications, regardless of whether they are generated by a human or AI technology."
          attribution="FINRA"
          sourceLabel="AI Created Communications"
          sourceUrl="https://www.finra.org/rules-guidance/guidance/faqs/advertising-regulation"
          supporting="AI changes who generates the communication. It does not change who is accountable for it."
        />

        <div className="lv-launch-paths">
          {PATHS.map((path, index) => (
            <ScrollReveal key={path.href} delay={index * 100}>
              <div className="lv-launch-path">
                <Link href={path.href} className="lv-launch-link">
                  {path.cta} <span aria-hidden="true">↗</span>
                </Link>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </div>
    </section>
  )
}
